default:
  image: emscripten/emsdk:4.0.0

stages:
  - build
  - test
  
build_filesystem:
  stage: build
  script:
    - cd src/filesystem
    - make build
    # Confirm our files are there
    - test -e api/compiled.mjs
    - test -e api/compiled.wasm
  # Artifacts are to be kept between jobs
  artifacts:
    paths:
      - src/filesystem/api/compiled.mjs
      - src/filesystem/api/compiled.wasm
    expire_in: 1 week

test_artefact_persistence:
  stage: test
  script:
    # Ensure artifacts have persisted
    - test -e src/filesystem/api/compiled.mjs
    - test -e src/filesystem/api/compiled.wasm

test_filesystem:
  stage: test
  script:
    - apt-get update
    - apt-get install -y wget chromium
    - cd src
    - npm install
    - npm run start-server &
    # Wait for the server to start
    - until curl -s http://localhost:8080 > /dev/null; do echo "Waiting for server..."; sleep 1; done
    - npm run filesystem-test
