default:
  image: emscripten/emsdk:4.0.0

stages:
  - lint
  - build
  - validate
  - test

lint_filesystem_js:
  stage: lint
  script:
    - cd src/filesystem
    - npm install
    - npm run lint

lint_filesystem_c:
  stage: lint
  script:
    - cd src/filesystem
    - apt-get update && apt-get -y install clang-tidy cppcheck
    - make lint

lint_filesystem_tests:
  stage: lint
  script:
    - cd src/filesystem
    - npm install
    - npm run lint-tests

lint_processes:
  stage: lint
  script:
    - cd src/processes
    - npm install
    - npm run lint
  
build_filesystem:
  stage: build
  script:
    - cd src/filesystem
    - apt-get update && apt-get -y install meson ninja-build
    - meson setup --cross-file ../emscripten.ini ../../build/filesystem
    - ninja -C ../../build/filesystem
  # Artifacts are to be kept between jobs
  artifacts:
    paths:
      - build/filesystem/index.html
      - build/filesystem/index.js
      - build/filesystem/api.js
      - build/filesystem/definitions.js
      - build/filesystem/filesystem.js
      - build/filesystem/filesystem.wasm
    expire_in: 1 week

validate_artefact_persistence:
  stage: validate
  dependencies:
    - build_filesystem
  script:
    # Ensure artifacts have persisted
    - test -e build/filesystem/filesystem.js
    - test -e build/filesystem/filesystem.wasm
    - test -e build/filesystem/index.html
    - test -e build/filesystem/index.js
    - test -e build/filesystem/api.js
    - test -e build/filesystem/definitions.js
    - test -e build/filesystem/filesystem.js
    - test -e build/filesystem/filesystem.wasm

validate_wasm:
  stage: validate
  dependencies:
    - build_filesystem
  script:
    - apt-get update && apt-get install -y wabt
    - wasm-validate --enable-threads build/filesystem/filesystem.wasm

test_filesystem:
  stage: test
  script:
    - cat /etc/apt/sources.list
    - cat /etc/os-release
    - apt-get update
    - apt-get install -y ca-certificates wget xdg-utils chromium-browser libgbm1
    - cd src/filesystem
    - npm install
    - npm run start-server ../../build/filesystem &
    # Wait for the server to start
    - until curl -s http://localhost:8080 > /dev/null; do echo "Waiting for server..."; sleep 1; done
    - npm run test
