default:
  image: emscripten/emsdk:4.0.0

stages:
  - build
  - test
  
build_filesystem:
  stage: build
  script:
    - cd src/filesystem
    - make build
    # Confirm our files are there
    - test -e api/compiled.mjs
    - test -e api/compiled.wasm
  # Artifacts are to be kept between jobs
  artifacts:
    paths:
      - src/filesystem/api/compiled.mjs
      - src/filesystem/api/compiled.wasm
    expire_in: 1 week

test_artefact_persistence:
  stage: test
  script:
    # Ensure artifacts have persisted
    - test -e src/filesystem/api/compiled.mjs
    - test -e src/filesystem/api/compiled.wasm

test_filesystem:
  stage: test
  script:
    - cat /etc/apt/sources.list
    - cat /etc/os-release
    - lsb_release -a
    - apt-get update
    - apt-get install -y ca-certificates \
      fonts-liberation libasound2 libatk-bridge2.0-0 \
      libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
      libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 \
      libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 \
      libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 \
      libxcb1 libxcomposite1 libxcursor1 libxdamage1 \
      libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 \
      libxss1 libxtst6 lsb-release wget xdg-utils
    - cd src
    - npm install
    - npm run start-server &
    # Wait for the server to start
    - until curl -s http://localhost:8080 > /dev/null; do echo "Waiting for server..."; sleep 1; done
    - npm run filesystem-test
