cat \
experiments/HO-36-filesystem/WASM-Emscripten/idbfs/* \
experiments/HO-36-filesystem/WASM-Emscripten/misc/*.c \
experiments/HO-36-filesystem/Filesystem-Access-API/*.html \
experiments/HO-36-filesystem/Filesystem-Access-API/src/*.js \
experiments/HO-37-filesystem/index.html \
experiments/HO-37-filesystem/Makefile \
experiments/HO-37-filesystem/src/*.c \
experiments/HO-37-filesystem/filesystem/*.js \
experiments/HO-40-processes/intro-to-webworkers/* \
experiments/HO-40-processes/toggle-output/* \
src/filesystem/meson.build \
src/filesystem/Makefile \
src/filesystem/*.js \
src/filesystem/src/* \
src/filesystem/*.html \
src/filesystem/luaSource/* \
src/filesystem/api/* \
src/filesystem/tests/* \
src/processes/*.html \
src/processes/*.js \
src/processes/meson.build \
src/processes/Makefile \
src/processes/src/* \
src/processes/c/* \
src/processes/tests/* \
src/test/* \
src/runtime/src/* \
src/runtime/doc/api.lua \
src/runtime/js/* \
src/runtime/test/* \
src/runtime/meson.build \
src/site/src/*.css \
src/site/src/*.html \
src/site/src/components/* \
src/site/src/lib/* \
src/site/src/routes/* \
justfile \
src/emscripten.ini \
src/glue/* \
src/deapi/meson.build \
src/deapi/src/* \
src/deploy-server/* \
| wc -l
